import { CodegenConfig } from '@graphql-codegen/cli';
import * as process from 'process';

import { getDatabaseSlug } from '../../shared/utils/src/utilFunctions/getDatabaseSlug';

const config: CodegenConfig = {
  overwrite: true,
  schema: [
    {
      [`${process.env['NX_SCHEMA_PATH']}/query` as string]: {
        headers: {
          schema: 'true',
          slug: getDatabaseSlug(),
        },
      },
    },
  ],
  watch: true,
  documents: 'libs/employee-portal/data-access/src/lib/**/*.graphql',
  generates: {
    'libs/employee-portal/data-access/src/generated/graphql.ts': {
      plugins: [
        {
          add: {
            content: [
              '/* eslint-disable */',
              '//This Code is auto generated by graphql-codegen, DO NOT EDIT',
              '//You can update the queries or mutations in *.graphql to generate any new changes.',
            ],
          },
        },
        'typescript',
        'typescript-operations',
        'typescript-react-query',
      ],
      config: {
        scalars: {
          Time: 'string',
          Any: 'unknown',
          Cursor: 'string',
          InvalidData: 'Record<string, Array<string>>',
          Map: 'Record<string, unknown>',
          Date: 'string',
          Localized: 'Record<"local"|"en"|"np",string>',
        },
        enumsAsConst: true,
        skipTypename: true,
        inlineFragmentTypes: 'combine',
        fetcher: {
          func: './axiosHelper#useAxios',
          isReactHook: true,
        },
      },
    },
    'libs/employee-portal/data-access/graphql.schema.json': {
      plugins: ['introspection'],
    },
  },
};

export default config;
