export type Actions =
  | 'CREATE'
  | 'UPDATE'
  | 'VIEW'
  | 'DELETE'
  | 'EXPORT'
  | 'REVIEW'
  | 'APPROVED'
  | 'SHOW_IN_MENU';

export const ACL_KEYS = {
  CBS_MEMBERS_MEMBER: 'CBS_MEMBERS_MEMBER',
  CBS_MEMBERS_MEMBER_DETAIL: 'CBS_MEMBERS_MEMBER_DETAIL',
  CBB_MEMBERS_MEMBER_FEE: 'CBB_MEMBERS_MEMBER_FEE',
  CBS_MEMBERS_KYM_UPDATE: 'CBS_MEMBERS_KYM_UPDATE',
  CBS_MEMBERS_MEMBER_CLOSE: 'CBS_MEMBERS_MEMBER_CLOSE',
  CBS_SHARE_SHARE_ISSUE: 'CBS_SHARE_SHARE_ISSUE',
  CBS_SHARE_SHARE_RETURN: 'CBS_SHARE_SHARE_RETURN',
  CBS_SHARE_SHARE_BALANCE: 'CBS_SHARE_SHARE_BALANCE',
  CBS_SHARE_SHARE_REGISTER: 'CBS_SHARE_SHARE_REGISTER',
  CBS_SHARE_SHARE_CERTIFICATE: 'CBS_SHARE_SHARE_CERTIFICATE',
  CBS_SAVINGS_SAVING_ACCOUNT: 'CBS_SAVINGS_SAVING_ACCOUNT',
  CBS_SAVINGS_SAVING_PRODUCT: 'CBS_SAVINGS_SAVING_PRODUCT',
  CBS_SAVINGS_SAVING_ACCOUNT_CLOSE: 'CBS_SAVINGS_SAVING_ACCOUNT_CLOSE',
  CBS_SAVINGS_SAVING_ACCOUNT_RENEW: 'CBS_SAVINGS_SAVING_ACCOUNT_RENEW',
  CBS_SAVINGS_FD_CERTIFICATE_PRINT: 'CBS_SAVINGS_FD_CERTIFICATE_PRINT',
  CBS_SAVINGS_SAVING_INTEREST_RATE_CHANGE: 'CBS_SAVINGS_SAVING_INTEREST_RATE_CHANGE',
  CBS_SAVINGS_SAVING_INTEREST_POST: 'CBS_SAVINGS_SAVING_INTEREST_POST',
  CBS_LOAN_LOAN_APPLICATION: 'CBS_LOAN_LOAN_APPLICATION',
  CBS_LOAN_LOAN_DISBURSEMENT: 'CBS_LOAN_LOAN_DISBURSEMENT',
  CBS_LOAN_LOAN_ACCOUNT: 'CBS_LOAN_LOAN_ACCOUNT',
  CBS_LOAN_LOAN_RENEW_OR_RESCHEDULE: 'CBS_LOAN_LOAN_RENEW_OR_RESCHEDULE',
  CBS_LOAN_LOAN_COLLATERAL_RELEASE: 'CBS_LOAN_LOAN_COLLATERAL_RELEASE',
  CBS_LOAN_LOAN_ACCOUNT_CLOSE: 'CBS_LOAN_LOAN_ACCOUNT_CLOSE',
  CBS_LOAN_DECLINED_LOAN: 'CBS_LOAN_DECLINED_LOAN',
  CBS_LOAN_LOAN_INTEREST_RATE_CHANGE: 'CBS_LOAN_LOAN_INTEREST_RATE_CHANGE',
  CBS_LOAN_LOAN_INTEREST_POST: 'CBS_LOAN_LOAN_INTEREST_POST',
  CBS_TRANSACTIONS_DEPOSIT: 'CBS_TRANSACTIONS_DEPOSIT',
  CBS_TRANSACTIONS_WITHDRAW: 'CBS_TRANSACTIONS_WITHDRAW',
  CBS_TRANSACTIONS_ACCOUNT_TRANSFER: 'CBS_TRANSACTIONS_ACCOUNT_TRANSFER',
  CBS_TRANSACTIONS_LOAN_REPAYMENT: 'CBS_TRANSACTIONS_LOAN_REPAYMENT',
  CBS_TRANSACTIONS_JOURNAL_VOUCHER: 'CBS_TRANSACTIONS_JOURNAL_VOUCHER',
  CBS_TRANSACTIONS_MARKET_REPRESENTATIVE_COLLECTION:
    'CBS_TRANSACTIONS_MARKET_REPRESENTATIVE_COLLECTION',
  CBS_TRANSACTIONS_BULK_ACCOUNT_TRANSFER: 'CBS_TRANSACTIONS_BULK_ACCOUNT_TRANSFER',
  CBS_TRANSACTION_LIMIT_SHARE: 'CBS_TRANSACTION_LIMIT_SHARE',
  CBS_TRANSACTION_LIMIT_DEPOSIT_LIMIT: 'CBS_TRANSACTION_LIMIT_DEPOSIT_LIMIT',
  CBS_TRANSACTION_LIMIT_WITHDRAW_LIMIT: 'CBS_TRANSACTION_LIMIT_WITHDRAW_LIMIT',
  CBS_TRANSACTION_LIMIT_LOAN_DISBURSE: 'CBS_TRANSACTION_LIMIT_LOAN_DISBURSE',
  CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES: 'CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES',
  CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_TODAY_COLLECTION_SHEET:
    'CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_TODAY_COLLECTION_SHEET',
  CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_MEMBER_ASSIGNMENT:
    'CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_MEMBER_ASSIGNMENT',
  CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_DAY_CLOSE:
    'CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_DAY_CLOSE',
  CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_PROFIT_TO_FUND_MANAGEMENT:
    'CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_PROFIT_TO_FUND_MANAGEMENT',
  CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_SHARE_DIVIDEND_POSTING:
    'CBS_MISCELLANEOUS_MARKET_REPRESENTATIVES_SHARE_DIVIDEND_POSTING',
  CBS_TRANSFERS_VAULT_TRANSFER: 'CBS_TRANSFERS_VAULT_TRANSFER',
  CBS_TRANSFERS_TELLER_TRANSFER: 'CBS_TRANSFERS_TELLER_TRANSFER',
  CBS_TRANSFERS_BRANCH_TRANSFER: 'CBS_TRANSFERS_BRANCH_TRANSFER',
  CBS_REQUESTS_MEMBER_REQUESTS: 'CBS_REQUESTS_MEMBER_REQUESTS',
  CBS_REQUESTS_WITHDRAW_REQUEST: 'CBS_REQUESTS_WITHDRAW_REQUEST',
  CBS_REQUESTS_LOAN_REQUESTS: 'CBS_REQUESTS_LOAN_REQUESTS',
  CBS_WITHDRAW_SLIPS_WITHDRAW_SLIPS_REQUESTS: 'CBS_WITHDRAW_SLIPS_WITHDRAW_SLIPS_REQUESTS',
  CBS_WITHDRAW_SLIPS_WITHDRAW_SLIPS_ISSUE: 'CBS_WITHDRAW_SLIPS_WITHDRAW_SLIPS_ISSUE',
  ACCOUNTING_SYSTEM_SALES_SALES_ENTRY: 'ACCOUNTING_SYSTEM_SALES_SALES_ENTRY',
  ACCOUNTING_SYSTEM_SALES_CREDIT_NOTE: 'ACCOUNTING_SYSTEM_SALES_CREDIT_NOTE',
  ACCOUNTING_SYSTEM_SALES_CUSTOMER_PAYMENT: 'ACCOUNTING_SYSTEM_SALES_CUSTOMER_PAYMENT',
  ACCOUNTING_SYSTEM_SALES_CUSTOMERS: 'ACCOUNTING_SYSTEM_SALES_CUSTOMERS',
  ACCOUNTING_SYSTEM_PURCHASE_PURCHASE_ENTRY: 'ACCOUNTING_SYSTEM_PURCHASE_PURCHASE_ENTRY',
  ACCOUNTING_SYSTEM_PURCHASE_EXPENSES: 'ACCOUNTING_SYSTEM_PURCHASE_EXPENSES',
  ACCOUNTING_SYSTEM_PURCHASE_DEBIT_NOTE: 'ACCOUNTING_SYSTEM_PURCHASE_DEBIT_NOTE',
  ACCOUNTING_SYSTEM_PURCHASE_SUPPLIER_PAYMENT: 'ACCOUNTING_SYSTEM_PURCHASE_SUPPLIER_PAYMENT',
  ACCOUNTING_SYSTEM_PURCHASE_SUPPLIERS: 'ACCOUNTING_SYSTEM_PURCHASE_SUPPLIERS',
  ACCOUNTING_SYSTEM_ACCOUNTING_JOURNAL_ENTRY: 'ACCOUNTING_SYSTEM_ACCOUNTING_JOURNAL_ENTRY',
  ACCOUNTING_SYSTEM_ACCOUNTING_QUICK_PAYMENT: 'ACCOUNTING_SYSTEM_ACCOUNTING_QUICK_PAYMENT',
  ACCOUNTING_SYSTEM_ACCOUNTING_QUICK_RECEIPT: 'ACCOUNTING_SYSTEM_ACCOUNTING_QUICK_RECEIPT',
  ACCOUNTING_SYSTEM_ACCOUNTING_BANK_ACCOUNTS: 'ACCOUNTING_SYSTEM_ACCOUNTING_BANK_ACCOUNTS',
  ACCOUNTING_SYSTEM_ACCOUNTING_BANK_TRANSACTIONS: 'ACCOUNTING_SYSTEM_ACCOUNTING_BANK_TRANSACTIONS',
  ACCOUNTING_SYSTEM_ACCOUNTING_CHARTS_OF_ACCOUNTS:
    'ACCOUNTING_SYSTEM_ACCOUNTING_CHARTS_OF_ACCOUNTS',
  ACCOUNTING_SYSTEM_INVESTMENTS: 'ACCOUNTING_SYSTEM_INVESTMENTS',
  ACCOUNTING_SYSTEM_INVESTMENTS_ACCOUNTS: 'ACCOUNTING_SYSTEM_INVESTMENTS_ACCOUNTS',
  ACCOUNTING_SYSTEM_INVESTMENT_TRANSACTIONS: 'ACCOUNTING_SYSTEM_INVESTMENT_TRANSACTIONS',
  ACCOUNTING_SYSTEM_EXTERNAL_LOAN: 'ACCOUNTING_SYSTEM_EXTERNAL_LOAN',
  ACCOUNTING_SYSTEM_EXTERNAL_LOAN_ACCOUNTS: 'ACCOUNTING_SYSTEM_EXTERNAL_LOAN_ACCOUNTS',
  ACCOUNTING_SYSTEM_EXTERNAL_LOAN_PAYMENTS: 'ACCOUNTING_SYSTEM_EXTERNAL_LOAN_PAYMENTS',

  ALTERNATIVE_CHANNELS_MOBILE_BANKING_REGISTRATION:
    'ALTERNATIVE_CHANNELS_MOBILE_BANKING_REGISTRATION',
  ALTERNATIVE_CHANNELS_E_BANKING_REGISTRATION: 'ALTERNATIVE_CHANNELS_E_BANKING_REGISTRATION',
  ALTERNATIVE_CHANNELS_ATM_CARD_REGISTRATION: 'ALTERNATIVE_CHANNELS_ATM_CARD_REGISTRATION',
  ALTERNATIVE_CHANNELS_SMS_REGISTRATION: 'ALTERNATIVE_CHANNELS_SMS_REGISTRATION',

  USER_USER: 'USER_USER',
  USER_USER_PASSWORD: 'USER_USER_PASSWORD',
  SETTINGS_ORGANIZATION_PROFILE: 'SETTINGS_ORGANIZATION_PROFILE',
  SETTINGS_SERVICE_CENTER: 'SETTINGS_SERVICE_CENTER',
  SETTINGS_COA: 'SETTINGS_COA',
  SETTINGS_MEMBER: 'SETTINGS_MEMBER',
  SETTINGS_KYM_SETTING: 'SETTINGS_KYM_SETTING',
  SETTINGS_SHARE: 'SETTINGS_SHARE',
  SETTINGS_SAVING_PARAMETERS: 'SETTINGS_SAVING_PARAMETERS',
  SETTINGS_SAVING_PRODUCTS: 'SETTINGS_SAVING_PRODUCTS',
  SETTINGS_LOAN_PARAMETERS: 'SETTINGS_LOAN_PARAMETERS',
  SETTINGS_LOAN_PRODUCTS: 'SETTINGS_LOAN_PRODUCTS',
  SETTINGS_DOCUMENT_MANAGEMENT: 'SETTINGS_DOCUMENT_MANAGEMENT',
  SETTINGS_INSURANCE: 'SETTINGS_INSURANCE',

  //

  CBS_SHARE: 'CBS_SHARE',
  CBS_SAVINGS: 'CBS_SAVINGS',
  CBS_LOAN: 'CBS_LOAN',
  CBS_TRANSACTIONS: 'CBS_TRANSACTIONS',
  CBS_TRANSFERS: 'CBS_TRANSFERS',
  CBS_REQUESTS: 'CBS_REQUESTS',
  CBS_WITHDRAWSLIP: 'CBS_WITHDRAWSLIP',
  CBS_REPORTS: 'CBS_REPORTS',
  CBS_OTHERS: 'CBS_OTHERS',

  CBS_TRANSFERS_CASH_IN_TRANSIT_TRANSFER: 'CBS_TRANSFERS_CASH_IN_TRANSIT_TRANSFER',
  CBS_WITHDRAW_SLIPS_WITHDRAW_SLIPS_BLOCK_REQUESTS:
    'CBS_WITHDRAW_SLIPS_WITHDRAW_SLIPS_BLOCK_REQUESTS',

  SETTINGS_AUDIT_LOG: 'SETTINGS_AUDIT_LOG',
  SETTINGS_BANK: 'SETTINGS_BANK',
  SETTINGS_CODE_MANAGEMENT: 'SETTINGS_CODE_MANAGEMENT',
  SETTINGS_ALTERNATIVE_CHANNELS: 'SETTINGS_ALTERNATIVE_CHANNELS',
  SETTINGS_INDEXING: 'SETTINGS_INDEXING',

  SETTINGS_GENERAL: 'SETTINGS_GENERAL',
  SETTINGS_USERS: 'SETTINGS_USERS',

  ALTERNATIVE_CHANNELS_USERS: 'ALTERNATIVE_CHANNELS_USERS',
  ALTERNATIVE_CHANNELS_DOWNLOADS: 'ALTERNATIVE_CHANNELS_DOWNLOADS',

  ACCOUNTING_SALES: 'ACCOUNTING_SALES',
  ACCOUNTING_PURCHASE: 'ACCOUNTING_PURCHASE',
  ACCOUNTING_ACCOUNTING: 'ACCOUNTING_ACCOUNTING',
  ACCOUNTING_LOAN: 'ACCOUNTING_LOAN',
  ACCOUNTING_INVESTMENT: 'ACCOUNTING_INVESTMENT',
  ACCOUNTING_SYSTEM_ACCOUNTING_CASH_TRANSFER: 'ACCOUNTING_SYSTEM_ACCOUNTING_CASH_TRANSFER',
} as const;

export type Subjects = keyof typeof ACL_KEYS;
export type AclKey = Subjects;
