kind: pipeline
name: Build all the apps - dev
type: docker

platform:
  arch: amd64
  os: linux

steps:
  - name: build affected modules - dev
    image: node:16
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
      - name: commit-sha
        path: /drone/previous-success-build-commit-sha
      - name: env-file-erp
        path: /drone/src/apps/myra/.env
      - name: env-file-ebanking
        path: /drone/src/apps/ebanking/.env
      - name: env-file-neosys
        path: /drone/src/apps/neosys-admin/.env
      - name: ebanking-app
        path: /drone/src/apps/ebanking/dist
      - name: myra-app
        path: /drone/src/apps/myra/dist
      - name: neosys-admin-app
        path: /drone/src/apps/neosys-admin/dist
    commands:
      # - npm cache --force clean
      # - npm install --force --cache
      # - yarn install --cache /tmp/empty-cache
      - yarn
      - npx nx affected --target=build --parallel --base=$(cat /drone/previous-success-build-commit-sha) --head=HEAD --verbose

volumes:
  - name: node_modules
    host:
      path: /build-cache/myra-ui-dev/node_modules
  - name: commit-sha
    host:
      path: /build-cache/myra-ui-dev/previous-success-build-commit-sha
  - name: env-file-erp
    host:
      path: /build-cache/myra-ui-dev/.env.erp
  - name: env-file-ebanking
    host:
      path: /build-cache/myra-ui-dev/.env.ebanking
  - name: env-file-neosys
    host:
      path: /build-cache/myra-ui-dev/.env.neosys
  - name: ebanking-app
    host:
      path: /build-cache/myra-ui-dev/ebanking-app
  - name: myra-app
    host:
      path: /build-cache/myra-ui-dev/myra-app
  - name: neosys-admin-app
    host:
      path: /build-cache/myra-ui-dev/neosys-admin-app

trigger:
  branch:
    - dev
  event:
    - push

---
kind: pipeline
name: Build storybook
type: docker

platform:
  arch: amd64
  os: linux

steps:
  - name: build storybook
    image: node:16
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
      - name: commit-sha
        path: /drone/previous-success-build-commit-sha
      - name: storybook-build
        path: /drone/src/dist
    commands:
      - yarn
      - npx nx affected --target=build-storybook --parallel --base=$(cat /drone/previous-success-build-commit-sha) --head=HEAD

volumes:
  - name: node_modules
    host:
      path: /build-cache/myra-ui-dev/node_modules
  - name: commit-sha
    host:
      path: /build-cache/myra-ui-dev/previous-success-build-commit-sha
  - name: storybook-build
    host:
      path: /build-cache/myra-ui-dev/storybook
depends_on:
  - Build all the apps - dev

trigger:
  branch:
    - dev
  event:
    - push

---
kind: pipeline
name: Publish myra-app - dev
type: docker

platform:
  arch: amd64
  os: linux

steps:
  - name: publishing myra-app - dev
    image: plugins/ecr
    settings:
      cache_from:
        - 110278083494.dkr.ecr.ap-southeast-1.amazonaws.com/myra-ui:dev
      access_key:
        from_secret: aws_access_key
      secret_key:
        from_secret: aws_secret_key
      repo: myra-ui
      registry: 110278083494.dkr.ecr.us-east-1.amazonaws.com
      region: us-east-1
      tags: dev
      context: /drone/src/apps/myra
      dockerfile: /drone/src/apps/myra/Dockerfile
    volumes:
      - name: myra-app
        path: /drone/src/apps/myra/dist
      - name: docker-sock
        path: /var/run/docker.sock

volumes:
  - name: myra-app
    host:
      path: /build-cache/myra-ui-dev/myra-app
  - name: docker-sock
    host:
      path: /var/run/docker.sock

depends_on:
  - Build all the apps - dev

trigger:
  branch:
    - dev
  event:
    - push

---
kind: pipeline
name: Publish neosys-admin-app - dev
type: docker

platform:
  arch: amd64
  os: linux

steps:
  - name: publishing neosys-admin-app - dev
    image: plugins/ecr
    settings:
      cache_from:
        - 110278083494.dkr.ecr.ap-southeast-1.amazonaws.com/myra-ui-admin:dev
      access_key:
        from_secret: aws_access_key
      secret_key:
        from_secret: aws_secret_key
      repo: myra-ui-admin
      registry: 110278083494.dkr.ecr.us-east-1.amazonaws.com
      region: us-east-1
      tags: dev
      context: /drone/src/apps/neosys-admin
      dockerfile: /drone/src/apps/neosys-admin/Dockerfile
    volumes:
      - name: neosys-admin-app
        path: /drone/src/apps/neosys-admin/dist
      - name: docker-sock
        path: /var/run/docker.sock

volumes:
  - name: neosys-admin-app
    host:
      path: /build-cache/myra-ui-dev/neosys-admin-app
  - name: docker-sock
    host:
      path: /var/run/docker.sock

depends_on:
  - Build all the apps - dev

trigger:
  branch:
    - dev
  event:
    - push

---
kind: pipeline
name: Publish ebanking-app - dev
type: docker

platform:
  arch: amd64
  os: linux

steps:
  - name: publishing ebanking-app - dev
    image: plugins/ecr
    settings:
      cache_from:
        - 110278083494.dkr.ecr.ap-southeast-1.amazonaws.com/myra-ui-ebanking:dev
      access_key:
        from_secret: aws_access_key
      secret_key:
        from_secret: aws_secret_key
      repo: myra-ui-ebanking
      registry: 110278083494.dkr.ecr.us-east-1.amazonaws.com
      region: us-east-1
      tags: dev
      context: /drone/src/apps/ebanking
      dockerfile: /drone/src/apps/ebanking/Dockerfile
    volumes:
      - name: ebanking-app
        path: /drone/src/apps/ebanking/dist
      - name: docker-sock
        path: /var/run/docker.sock

volumes:
  - name: ebanking-app
    host:
      path: /build-cache/myra-ui-dev/ebanking-app
  - name: docker-sock
    host:
      path: /var/run/docker.sock

depends_on:
  - Build all the apps - dev

trigger:
  branch:
    - dev
  event:
    - push

---
kind: pipeline
name: Publish storybook
type: docker

platform:
  arch: amd64
  os: linux

steps:
  - name: publishing storybook
    image: plugins/ecr
    settings:
      cache_from:
        - 110278083494.dkr.ecr.ap-southeast-1.amazonaws.com/storybook:dev
      access_key:
        from_secret: aws_access_key
      secret_key:
        from_secret: aws_secret_key
      repo: storybook
      registry: 110278083494.dkr.ecr.us-east-1.amazonaws.com
      region: us-east-1
      tags: dev
      dockerfile: /drone/src/Dockerfile.storybook
    volumes:
      - name: storybook
        path: /drone/src/dist
      - name: docker-sock
        path: /var/run/docker.sock

volumes:
  - name: storybook
    host:
      path: /build-cache/myra-ui-dev/storybook
  - name: docker-sock
    host:
      path: /var/run/docker.sock

depends_on:
  - Build storybook

trigger:
  branch:
    - dev
  event:
    - push

---
kind: pipeline
type: ssh
name: Pull images and deploy all the apps - dev

server:
  host:
    from_secret: hostname
  user:
    from_secret: host_user
  ssh_key:
    from_secret: ssh_key

steps:
  - name: deploy all the apps - dev
    environment:
      access_key:
        from_secret: aws_access_key
      secret_key:
        from_secret: aws_secret_key
    commands:
      - cp /apps/myra-ui-dev/.env .
      - aws configure set aws_access_key_id $access_key
      - aws configure set aws_secret_access_key $secret_key
      - aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin 110278083494.dkr.ecr.us-east-1.amazonaws.com
      - docker-compose -f docker-compose.neosys.yml pull
      - docker-compose -f docker-compose.ebanking.yml pull
      - docker-compose -f docker-compose.myra.yml pull
      - docker-compose -f docker-compose.storybook.yml pull
      - docker-compose --project-name myra-ui-neosys-dev -f docker-compose.neosys.yml up --no-build --force-recreate -d
      - docker-compose --project-name myra-ui-ebanking-dev -f docker-compose.ebanking.yml up --no-build --force-recreate -d
      - docker-compose --project-name myra-ui-myra-dev -f docker-compose.myra.yml up --no-build --force-recreate -d
      - docker-compose --project-name myra-ui-storybook -f docker-compose.storybook.yml up --no-build --force-recreate -d
      - docker image prune -a -f || true
      - docker container prune -a -f || true

depends_on:
  - Publish myra-app - dev
  - Publish neosys-admin-app - dev
  - Publish ebanking-app - dev
  - Publish storybook

trigger:
  branch:
    - dev
  event:
    - push

---
kind: pipeline
type: docker
name: Update last successful build commit SHA - dev

steps:
  - name: update content in host file - dev
    image: alpine:latest
    volumes:
      - name: commit-sha
        path: /drone/previous-success-build-commit-sha
    commands:
      - echo $DRONE_COMMIT_SHA > /drone/previous-success-build-commit-sha

volumes:
  - name: commit-sha
    host:
      path: /build-cache/myra-ui-dev/previous-success-build-commit-sha

depends_on:
  - Pull images and deploy all the apps - dev
trigger:
  branch:
    - dev
  event:
    - push

---
#########################################################################################################
#########################################################################################################
####                          S T A G I N G   P I P E L I N E                                        ####
#########################################################################################################
#########################################################################################################

kind: pipeline
name: Build and Push myra
type: docker

platform:
  arch: amd64
  os: linux

steps:
- name: Build myra-ui
  image: node:16
  volumes:
  - name: myra-env-${DRONE_BRANCH}
    path: /drone/src/apps/myra/.env
  - name: docker-sock
    path: /var/run/docker.sock
  - name: myra-app
    path: /drone/src/apps/myra/dist
  commands:
  - yarn
  - npx nx run myra:build:production

- name: Breakpoint
  image: ubuntu
  volumes:
  - name: myra-app
    path: /drone/src/apps/myra
  - name: docker-sock
    path: /var/run/docker.sock
  commands:
  - sleep infinity

- name: Publish myra-ui
  image: bentolor/docker-dind-awscli:dind
  environment:
    aws_access_key:
      from_secret: aws_access_key
    aws_secret_key:
      from_secret: aws_secret_key
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  - name: myra-app
    path: /drone/src/apps/myra/dist
  commands:
  - aws configure set aws_access_key_id $aws_access_key
  - aws configure set aws_secret_access_key $aws_secret_key
  - aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin 110278083494.dkr.ecr.us-east-1.amazonaws.com
  - docker compose -f docker-compose.${DRONE_BRANCH}.yaml build myra
  - docker compose -f docker-compose.${DRONE_BRANCH}.yaml push myra

volumes:
- name: myra-env-${DRONE_BRANCH}
  host:
    path: /build-cache/myra-ui-${DRONE_BRANCH}/.env.erp
- name: docker-sock
  host:
    path: /var/run/docker.sock
- name: myra-app
  temp: {}

trigger:
  branch:
  - staging
  event:
  - push

---

kind: pipeline
name: Build and Push neosys
type: docker

platform:
  arch: amd64
  os: linux

steps:
- name: Build neosys-ui
  image: node:16
  volumes:
  - name: myra-env-${DRONE_BRANCH}
    path: /drone/src/apps/neosys-admin/.env
  - name: docker-sock
    path: /var/run/docker.sock
  - name: neosys-app
    path: /drone/src/apps/neosys-admin/dist
  commands:
  - yarn
  - npx nx run neosys-admin:build:production

- name: Publish neosys-ui
  image: bentolor/docker-dind-awscli:dind
  environment:
    aws_access_key:
      from_secret: aws_access_key
    aws_secret_key:
      from_secret: aws_secret_key
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  - name: neosys-app
    path: /drone/src/apps/neosys-admin/dist
  commands:
  - aws configure set aws_access_key_id $aws_access_key
  - aws configure set aws_secret_access_key $aws_secret_key
  - aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin 110278083494.dkr.ecr.us-east-1.amazonaws.com
  - docker compose -f docker-compose.${DRONE_BRANCH}.yaml build neosys-admin
  - docker compose -f docker-compose.${DRONE_BRANCH}.yaml push neosys-admin

volumes:
- name: myra-env-${DRONE_BRANCH}
  host:
    path: /build-cache/myra-ui-${DRONE_BRANCH}/.env.neosys
- name: docker-sock
  host:
    path: /var/run/docker.sock
- name: neosys-app
  temp: {}

trigger:
  branch:
  - staging
  event:
  - push

---

kind: pipeline
name: Build and Push ebanking
type: docker

platform:
  arch: amd64
  os: linux

steps:
- name: Build ebanking-ui
  image: node:16
  volumes:
  - name: myra-env-${DRONE_BRANCH}
    path: /drone/src/apps/ebanking/.env
  - name: docker-sock
    path: /var/run/docker.sock
  - name: ebanking-app
    path: /drone/src/apps/ebanking/dist
  commands:
  - yarn
  - npx nx run ebanking:build:production

- name: Publish ebanking-ui
  image: bentolor/docker-dind-awscli:dind
  environment:
    aws_access_key:
      from_secret: aws_access_key
    aws_secret_key:
      from_secret: aws_secret_key
  volumes:
  - name: docker-sock
    path: /var/run/docker.sock
  - name: ebanking-app
    path: /drone/src/apps/ebanking/dist
  commands:
  - aws configure set aws_access_key_id $aws_access_key
  - aws configure set aws_secret_access_key $aws_secret_key
  - aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin 110278083494.dkr.ecr.us-east-1.amazonaws.com
  - docker compose -f docker-compose.${DRONE_BRANCH}.yaml build ebanking
  - docker compose -f docker-compose.${DRONE_BRANCH}.yaml push ebanking

volumes:
- name: myra-env-${DRONE_BRANCH}
  host:
    path: /build-cache/myra-ui-${DRONE_BRANCH}/.env.ebanking
- name: docker-sock
  host:
    path: /var/run/docker.sock
- name: ebanking-app
  temp: {}

trigger:
  branch:
  - staging
  event:
  - push
