version: '3.5'

services:
  ebanking:
    build:
      context: apps/ebanking
      dockerfile: Dockerfile
    image: 110278083494.dkr.ecr.us-east-1.amazonaws.com/prod-ebanking:v1.0.5
    container_name: ebanking-ui-production
    ports:
      - 7000:3000
    restart: unless-stopped
    networks:
      - myra-frontend

  myra:
    build:
      context: apps/myra
      dockerfile: Dockerfile
    image: 110278083494.dkr.ecr.us-east-1.amazonaws.com/prod-myra:v1.0.5
    container_name: myra-ui-production
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - myra-frontend

  neosys-admin:
    build:
      context: apps/neosys-admin
      dockerfile: Dockerfile
    image: 110278083494.dkr.ecr.us-east-1.amazonaws.com/prod-neosys:v1.0.5
    container_name: admin-ui-production
    ports:
      - 5000:3000
    restart: unless-stopped
    networks:
      - myra-frontend

networks:
   myra-frontend:
      driver: bridge
