version: '3.5'

services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook
    image: 110278083494.dkr.ecr.us-east-1.amazonaws.com/storybook:main
    container_name: ${STORYBOOK_CONTAINER_NAME}
    ports:
      - ${STORYBOOK_PORT}:80
    restart: unless-stopped
