version: '3.5'

services:
  ebanking:
    build:
      context: apps/ebanking
      dockerfile: Dockerfile
    image: 110278083494.dkr.ecr.ap-south-1.amazonaws.com/prod-ebanking:${DRONE_TAG}

    container_name: ebanking-ui-production
    ports:
      - 7000:3000
    restart: unless-stopped
    networks:
      - myra-frontend

  myra:
    build:
      context: apps/myra
      dockerfile: Dockerfile
    image: 110278083494.dkr.ecr.ap-south-1.amazonaws.com/prod-myra:${DRONE_TAG}

    container_name: myra-ui-production
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - myra-frontend

  neosys-admin:
    build:
      context: apps/neosys-admin
      dockerfile: Dockerfile
    image: 110278083494.dkr.ecr.ap-south-1.amazonaws.com/prod-neosys:${DRONE_TAG}

    container_name: admin-ui-production
    ports:
      - 5000:3000
    restart: unless-stopped
    networks:
      - myra-frontend

networks:
  myra-frontend:
    driver: bridge
