version: '3.5'

services:
  ebanking:
    build:
      context: .
      dockerfile: apps/ebanking/Dockerfile
    image: 110278083494.dkr.ecr.us-east-1.amazonaws.com/prod-ebanking:staging
    container_name: ${EBANKING_CONTAINER_NAME}
    env_file: .env
    ports:
      - ${EBANKING_PORT}:3000
    restart: unless-stopped
    networks:
      - myra-frontend

  myra:
    build:
      context: .
      dockerfile: apps/myra/Dockerfile
    image: 110278083494.dkr.ecr.us-east-1.amazonaws.com/prod-myra:staging
    container_name: ${MYRA_CONTAINER_NAME}
    env_file: .env
    ports:
      - ${MYRA_PORT}:3000
    restart: unless-stopped
    networks:
      - myra-frontend

  neosys-admin:
    build:
      context: .
      dockerfile: apps/neosys-admin/Dockerfile
    image: 110278083494.dkr.ecr.us-east-1.amazonaws.com/prod-neosys:staging
    container_name: ${ADMIN_CONTAINER_NAME}
    env_file: .env
    ports:
      - ${ADMIN_PORT}:3000
    restart: unless-stopped
    networks:
      - myra-frontend

networks:
   myra-frontend:
      driver: bridge
