version: '3.5'

services:
  neosys-admin:
    build:
      context: .
      dockerfile: Dockerfile.neosys-admin
    image: 110278083494.dkr.ecr.us-east-1.amazonaws.com/myra-ui-admin:dev
    container_name: ${ADMIN_CONTAINER_NAME}
    env_file: .env
    ports:
      - ${ADMIN_PORT}:3000
    restart: unless-stopped
