version: '3.5'

services:
  migration:
    build:
      context: .
      dockerfile: apps/migration/Dockerfile
    image: 110278083494.dkr.ecr.ap-south-1.amazonaws.com/dev-migration:dev
    container_name: migration-ui
    env_file: apps/migration/.env
    ports:
      - 8081:3000
    restart: unless-stopped
