FROM node:14-alpine AS builder

WORKDIR /app

COPY package* .
COPY yarn.lock .

RUN yarn

COPY . .

RUN npx nx run shared-ui:build-storybook

FROM nginx:alpine AS server

RUN rm /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist/storybook/myra-ui /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
