version: '3.5'

services:
  ebanking:
    build:
      context: apps/ebanking
      dockerfile: Dockerfile
    image: 110278083494.dkr.ecr.ap-south-1.amazonaws.com/myra-ui-ebanking:dev
    container_name: ebanking-ui-staging
    ports:
      - 7000:3000
    restart: unless-stopped
    networks:
      - myra-frontend

  myra:
    build:
      context: apps/myra
      dockerfile: Dockerfile
    image: 110278083494.dkr.ecr.ap-south-1.amazonaws.com/myra-ui:dev
    container_name: myra-ui-staging
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - myra-frontend

  neosys-admin:
    build:
      context: apps/neosys-admin
      dockerfile: Dockerfile
    image: 110278083494.dkr.ecr.ap-south-1.amazonaws.com/myra-ui-admin:dev
    container_name: admin-ui-staging
    ports:
      - 5000:3000
    restart: unless-stopped
    networks:
      - myra-frontend

networks:
   myra-frontend:
      driver: bridge
