version: '3.5'

services:
  ebanking:
    build:
      context: .
      dockerfile: Dockerfile.ebanking
    container_name: ${EBANKING_CONTAINER_NAME}
    env_file: .env
    ports:
      - ${EBANKING_PORT}:3000
    restart: unless-stopped

