# Install dependencies only when needed
FROM node:16-alpine AS builder
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
WORKDIR /app

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

RUN npx nx run shared-ui:storybook
