#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#exec >/dev/tty 2>&1

# npm test
# npx --no-install commitlint --edit "$1"
echo 'commiting'
# yarn lint-staged

# pnpm test
npx lint-staged

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
